name: gdbserver builder

on:
  schedule:
    - cron: '24 14 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  GDB_VERSION: 11.2

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup gdb & buildroot env
        run: |
          sudo chmod +x ./setup_env.sh && sudo ./setup_env.sh
      
      - name: arm cross building
        run: |
          sudo chmod +x ./builder.sh && sudo ./builder.sh $GDB_VERSION arm

      - name: aarch64 cross building
        run: |
          sudo chmod +x ./builder.sh && sudo ./builder.sh $GDB_VERSION aarch64

      - name: mips cross building
        run: |
          sudo chmod +x ./builder.sh && sudo ./builder.sh $GDB_VERSION mips

      - name: mips64 cross building
        run: |
          sudo chmod +x ./builder.sh && sudo ./builder.sh $GDB_VERSION mips64

      - name: riscv64 cross building
        run: |
          sudo chmod +x ./builder.sh && sudo ./builder.sh $GDB_VERSION riscv64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /releases/*

      # - uses: shaowenchen/debugger-action@v1
      #   name: debugger
      #   timeout-minutes: 360
      #   continue-on-error: true
      #   with:
      #     frp_server_addr: 120.24.72.234
      #     frp_server_port: 7000
      #     frp_token: 12345678
      #     ssh_port: 7001